version: '3.8'
services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Josh@123
      MYSQL_DATABASE: humans
      MYSQL_USER: root
      MYSQL_PASSWORD: Josh@123
