spring:
  datasource:
    url: jdbc:mysql://localhost:3306/humans
    username: root
    password: Josh@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: create-drop
    show-sql: true
